//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA.otroPrueba {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", ConfigurationName="otroPrueba.ClienteWS")]
    public interface ClienteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/listarTodosClientesRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/listarTodosClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWA.otroPrueba.listarTodosClientesResponse listarTodosClientes(CreditoMovilWA.otroPrueba.listarTodosClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/listarTodosClientesRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/listarTodosClientesResponse")]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.listarTodosClientesResponse> listarTodosClientesAsync(CreditoMovilWA.otroPrueba.listarTodosClientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/obtenerPorIDClienteRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/obtenerPorIDClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWA.otroPrueba.obtenerPorIDClienteResponse obtenerPorIDCliente(CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/obtenerPorIDClienteRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/obtenerPorIDClienteResponse")]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.obtenerPorIDClienteResponse> obtenerPorIDClienteAsync(CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/insertarClienteParametrosRequ" +
            "est", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/insertarClienteParametrosResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWA.otroPrueba.insertarClienteParametrosResponse insertarClienteParametros(CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/insertarClienteParametrosRequ" +
            "est", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/insertarClienteParametrosResp" +
            "onse")]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.insertarClienteParametrosResponse> insertarClienteParametrosAsync(CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/eliminarClienteRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/eliminarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWA.otroPrueba.eliminarClienteResponse eliminarCliente(CreditoMovilWA.otroPrueba.eliminarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/eliminarClienteRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/eliminarClienteResponse")]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.eliminarClienteResponse> eliminarClienteAsync(CreditoMovilWA.otroPrueba.eliminarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/modificarClienteRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/modificarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWA.otroPrueba.modificarClienteResponse modificarCliente(CreditoMovilWA.otroPrueba.modificarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.creditomovil.pucp.edu.pe/ClienteWS/modificarClienteRequest", ReplyAction="https://services.creditomovil.pucp.edu.pe/ClienteWS/modificarClienteResponse")]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.modificarClienteResponse> modificarClienteAsync(CreditoMovilWA.otroPrueba.modificarClienteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://services.creditomovil.pucp.edu.pe")]
    public partial class cliente : usuario {
        
        private string codigoClienteField;
        
        private string direccionField;
        
        private string emailField;
        
        private string telefonoField;
        
        private string tipoClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://services.creditomovil.pucp.edu.pe")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apMaternoField;
        
        private string apPaternoField;
        
        private string contrasenhaField;
        
        private string documentoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private System.DateTime ultimoLogueoField;
        
        private bool ultimoLogueoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
                this.RaisePropertyChanged("apMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("apPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime ultimoLogueo {
            get {
                return this.ultimoLogueoField;
            }
            set {
                this.ultimoLogueoField = value;
                this.RaisePropertyChanged("ultimoLogueo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimoLogueoSpecified {
            get {
                return this.ultimoLogueoFieldSpecified;
            }
            set {
                this.ultimoLogueoFieldSpecified = value;
                this.RaisePropertyChanged("ultimoLogueoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://services.creditomovil.pucp.edu.pe")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        CARNET_EXTRANJERIA,
        
        /// <remarks/>
        PASAPORTE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosClientes", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosClientesRequest {
        
        public listarTodosClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosClientesResponse", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWA.otroPrueba.cliente[] @return;
        
        public listarTodosClientesResponse() {
        }
        
        public listarTodosClientesResponse(CreditoMovilWA.otroPrueba.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIDCliente", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerPorIDClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idcliente;
        
        public obtenerPorIDClienteRequest() {
        }
        
        public obtenerPorIDClienteRequest(string idcliente) {
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIDClienteResponse", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerPorIDClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWA.otroPrueba.cliente @return;
        
        public obtenerPorIDClienteResponse() {
        }
        
        public obtenerPorIDClienteResponse(CreditoMovilWA.otroPrueba.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarClienteParametros", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarClienteParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWA.otroPrueba.tipoDocumento tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoCliente;
        
        public insertarClienteParametrosRequest() {
        }
        
        public insertarClienteParametrosRequest(int idUsuario, System.DateTime fecha, string nombre, string apPaterno, string apMaterno, string contrasenha, System.DateTime fechaVencimiento, bool activo, CreditoMovilWA.otroPrueba.tipoDocumento tipoDocumento, string documento, string codigoCliente, string direccion, string telefono, string email, string tipoCliente) {
            this.idUsuario = idUsuario;
            this.fecha = fecha;
            this.nombre = nombre;
            this.apPaterno = apPaterno;
            this.apMaterno = apMaterno;
            this.contrasenha = contrasenha;
            this.fechaVencimiento = fechaVencimiento;
            this.activo = activo;
            this.tipoDocumento = tipoDocumento;
            this.documento = documento;
            this.codigoCliente = codigoCliente;
            this.direccion = direccion;
            this.telefono = telefono;
            this.email = email;
            this.tipoCliente = tipoCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarClienteParametrosResponse", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarClienteParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarClienteParametrosResponse() {
        }
        
        public insertarClienteParametrosResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCliente", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class eliminarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idcliente;
        
        public eliminarClienteRequest() {
        }
        
        public eliminarClienteRequest(string idcliente) {
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarClienteResponse", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class eliminarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarClienteResponse() {
        }
        
        public eliminarClienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCliente", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class modificarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWA.otroPrueba.cliente cliente;
        
        public modificarClienteRequest() {
        }
        
        public modificarClienteRequest(CreditoMovilWA.otroPrueba.cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarClienteResponse", WrapperNamespace="https://services.creditomovil.pucp.edu.pe", IsWrapped=true)]
    public partial class modificarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://services.creditomovil.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public modificarClienteResponse() {
        }
        
        public modificarClienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteWSChannel : CreditoMovilWA.otroPrueba.ClienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSClient : System.ServiceModel.ClientBase<CreditoMovilWA.otroPrueba.ClienteWS>, CreditoMovilWA.otroPrueba.ClienteWS {
        
        public ClienteWSClient() {
        }
        
        public ClienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWA.otroPrueba.listarTodosClientesResponse CreditoMovilWA.otroPrueba.ClienteWS.listarTodosClientes(CreditoMovilWA.otroPrueba.listarTodosClientesRequest request) {
            return base.Channel.listarTodosClientes(request);
        }
        
        public CreditoMovilWA.otroPrueba.cliente[] listarTodosClientes() {
            CreditoMovilWA.otroPrueba.listarTodosClientesRequest inValue = new CreditoMovilWA.otroPrueba.listarTodosClientesRequest();
            CreditoMovilWA.otroPrueba.listarTodosClientesResponse retVal = ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).listarTodosClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.listarTodosClientesResponse> CreditoMovilWA.otroPrueba.ClienteWS.listarTodosClientesAsync(CreditoMovilWA.otroPrueba.listarTodosClientesRequest request) {
            return base.Channel.listarTodosClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.listarTodosClientesResponse> listarTodosClientesAsync() {
            CreditoMovilWA.otroPrueba.listarTodosClientesRequest inValue = new CreditoMovilWA.otroPrueba.listarTodosClientesRequest();
            return ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).listarTodosClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWA.otroPrueba.obtenerPorIDClienteResponse CreditoMovilWA.otroPrueba.ClienteWS.obtenerPorIDCliente(CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest request) {
            return base.Channel.obtenerPorIDCliente(request);
        }
        
        public CreditoMovilWA.otroPrueba.cliente obtenerPorIDCliente(string idcliente) {
            CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest inValue = new CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest();
            inValue.idcliente = idcliente;
            CreditoMovilWA.otroPrueba.obtenerPorIDClienteResponse retVal = ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).obtenerPorIDCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.obtenerPorIDClienteResponse> CreditoMovilWA.otroPrueba.ClienteWS.obtenerPorIDClienteAsync(CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest request) {
            return base.Channel.obtenerPorIDClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.obtenerPorIDClienteResponse> obtenerPorIDClienteAsync(string idcliente) {
            CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest inValue = new CreditoMovilWA.otroPrueba.obtenerPorIDClienteRequest();
            inValue.idcliente = idcliente;
            return ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).obtenerPorIDClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWA.otroPrueba.insertarClienteParametrosResponse CreditoMovilWA.otroPrueba.ClienteWS.insertarClienteParametros(CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest request) {
            return base.Channel.insertarClienteParametros(request);
        }
        
        public bool insertarClienteParametros(int idUsuario, System.DateTime fecha, string nombre, string apPaterno, string apMaterno, string contrasenha, System.DateTime fechaVencimiento, bool activo, CreditoMovilWA.otroPrueba.tipoDocumento tipoDocumento, string documento, string codigoCliente, string direccion, string telefono, string email, string tipoCliente) {
            CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest inValue = new CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest();
            inValue.idUsuario = idUsuario;
            inValue.fecha = fecha;
            inValue.nombre = nombre;
            inValue.apPaterno = apPaterno;
            inValue.apMaterno = apMaterno;
            inValue.contrasenha = contrasenha;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.activo = activo;
            inValue.tipoDocumento = tipoDocumento;
            inValue.documento = documento;
            inValue.codigoCliente = codigoCliente;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.tipoCliente = tipoCliente;
            CreditoMovilWA.otroPrueba.insertarClienteParametrosResponse retVal = ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).insertarClienteParametros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.insertarClienteParametrosResponse> CreditoMovilWA.otroPrueba.ClienteWS.insertarClienteParametrosAsync(CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest request) {
            return base.Channel.insertarClienteParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.insertarClienteParametrosResponse> insertarClienteParametrosAsync(int idUsuario, System.DateTime fecha, string nombre, string apPaterno, string apMaterno, string contrasenha, System.DateTime fechaVencimiento, bool activo, CreditoMovilWA.otroPrueba.tipoDocumento tipoDocumento, string documento, string codigoCliente, string direccion, string telefono, string email, string tipoCliente) {
            CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest inValue = new CreditoMovilWA.otroPrueba.insertarClienteParametrosRequest();
            inValue.idUsuario = idUsuario;
            inValue.fecha = fecha;
            inValue.nombre = nombre;
            inValue.apPaterno = apPaterno;
            inValue.apMaterno = apMaterno;
            inValue.contrasenha = contrasenha;
            inValue.fechaVencimiento = fechaVencimiento;
            inValue.activo = activo;
            inValue.tipoDocumento = tipoDocumento;
            inValue.documento = documento;
            inValue.codigoCliente = codigoCliente;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.tipoCliente = tipoCliente;
            return ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).insertarClienteParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWA.otroPrueba.eliminarClienteResponse CreditoMovilWA.otroPrueba.ClienteWS.eliminarCliente(CreditoMovilWA.otroPrueba.eliminarClienteRequest request) {
            return base.Channel.eliminarCliente(request);
        }
        
        public bool eliminarCliente(string idcliente) {
            CreditoMovilWA.otroPrueba.eliminarClienteRequest inValue = new CreditoMovilWA.otroPrueba.eliminarClienteRequest();
            inValue.idcliente = idcliente;
            CreditoMovilWA.otroPrueba.eliminarClienteResponse retVal = ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).eliminarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.eliminarClienteResponse> CreditoMovilWA.otroPrueba.ClienteWS.eliminarClienteAsync(CreditoMovilWA.otroPrueba.eliminarClienteRequest request) {
            return base.Channel.eliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.eliminarClienteResponse> eliminarClienteAsync(string idcliente) {
            CreditoMovilWA.otroPrueba.eliminarClienteRequest inValue = new CreditoMovilWA.otroPrueba.eliminarClienteRequest();
            inValue.idcliente = idcliente;
            return ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).eliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWA.otroPrueba.modificarClienteResponse CreditoMovilWA.otroPrueba.ClienteWS.modificarCliente(CreditoMovilWA.otroPrueba.modificarClienteRequest request) {
            return base.Channel.modificarCliente(request);
        }
        
        public bool modificarCliente(CreditoMovilWA.otroPrueba.cliente cliente) {
            CreditoMovilWA.otroPrueba.modificarClienteRequest inValue = new CreditoMovilWA.otroPrueba.modificarClienteRequest();
            inValue.cliente = cliente;
            CreditoMovilWA.otroPrueba.modificarClienteResponse retVal = ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).modificarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.modificarClienteResponse> CreditoMovilWA.otroPrueba.ClienteWS.modificarClienteAsync(CreditoMovilWA.otroPrueba.modificarClienteRequest request) {
            return base.Channel.modificarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWA.otroPrueba.modificarClienteResponse> modificarClienteAsync(CreditoMovilWA.otroPrueba.cliente cliente) {
            CreditoMovilWA.otroPrueba.modificarClienteRequest inValue = new CreditoMovilWA.otroPrueba.modificarClienteRequest();
            inValue.cliente = cliente;
            return ((CreditoMovilWA.otroPrueba.ClienteWS)(this)).modificarClienteAsync(inValue);
        }
    }
}
