//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class DetalleCredito
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.TextBox txtFechaOtorgamiento;
        protected global::System.Web.UI.WebControls.TextBox txtEstado;
        protected global::System.Web.UI.WebControls.TextBox txtMonto;
        protected global::System.Web.UI.WebControls.TextBox txtNumeroCuotas;
        protected global::System.Web.UI.WebControls.TextBox txtTasaInteres;
        protected global::System.Web.UI.WebControls.GridView gvTransacciones;
        protected global::System.Web.UI.WebControls.Button btnRegresar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl idCredito;
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;
    }

}
