//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class DetalleEvaluacion
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblNumeroEvaluacion;
        protected global::System.Web.UI.WebControls.TextBox txtNombreNegocio;
        protected global::System.Web.UI.WebControls.TextBox txtFechaRegistro;
        protected global::System.Web.UI.WebControls.TextBox txtDireccionNegocio;
        protected global::System.Web.UI.WebControls.TextBox txtTelefonoNegocio;
        protected global::System.Web.UI.WebControls.TextBox txtClienteAsignado;
        protected global::System.Web.UI.WebControls.TextBox txtMargenGanancia;
        protected global::System.Web.UI.WebControls.TextBox txtVentasDiarias;
        protected global::System.Web.UI.WebControls.TextBox txtInventario;
        protected global::System.Web.UI.WebControls.TextBox txtCostoVentas;
        protected global::System.Web.UI.WebControls.TextBox txtEstado;
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
        protected global::System.Web.UI.WebControls.Label lblPuntaje;
        protected global::System.Web.UI.WebControls.Button btnModificar;
        protected global::System.Web.UI.WebControls.Button btnRegresar;
    }
}
