//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class DetalleTransaccion
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlForm mainForm;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.TextBox txtIdTransaccion;
        protected global::System.Web.UI.WebControls.TextBox txtFechaTransaccion;
        protected global::System.Web.UI.WebControls.TextBox txtAgenciaTransaccion;
        protected global::System.Web.UI.WebControls.TextBox txtMonto;
        protected global::System.Web.UI.WebControls.FileUpload fileUploadImagen;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
