//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class MainCliente
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Label lblRanking;
        protected global::System.Web.UI.WebControls.Label dtsSupervisor;
        protected global::System.Web.UI.WebControls.Button btnSolicitarCredito;
        protected global::System.Web.UI.WebControls.Button btnVerCreditos;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl hola;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl contInicial;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl contCotidiano;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl apexGauge;
       
    }
}
