//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class MainSupervisor
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gvEvaluacionesRealizadas;
        protected global::System.Web.UI.WebControls.GridView gvEvaluacionesPendientes;
        protected global::System.Web.UI.WebControls.GridView gvClientesCredPend;
        protected global::System.Web.UI.WebControls.GridView gvCredPendXCli;
        protected global::System.Web.UI.WebControls.Button btnDetallesCliente;
        protected global::System.Web.UI.WebControls.Button btnVerCreditos;
        protected global::System.Web.UI.WebControls.Button btnAprobarCredito;
        protected global::System.Web.UI.WebControls.Button btnVerDetalleEv;
        protected global::System.Web.UI.WebControls.Button btnAprobarEv;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Label txtCliPendAsig;
        protected global::System.Web.UI.WebControls.Label txtNotClientPend;
        protected global::System.Web.UI.WebControls.Label txtHayPendiente;
        protected global::System.Web.UI.WebControls.Label txtNoHayPendiente;
        protected global::System.Web.UI.WebControls.Label txtHayRealizado;
        protected global::System.Web.UI.WebControls.Label txtNoHayEvRealizada;

    }
}
