//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class MainSupervisor
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gvEvaluacionesRealizadas;
        protected global::System.Web.UI.WebControls.GridView gvEvaluacionesPendientes;
        protected global::System.Web.UI.WebControls.GridView gvClientesCredPend;
        protected global::System.Web.UI.WebControls.GridView gvCredPendXCli;
        protected global::System.Web.UI.WebControls.Button btnVerDetalle;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Button cliPendAsig;
        protected global::System.Web.UI.WebControls.Button txtCliPendAsig;
        protected global::System.Web.UI.WebControls.Button txtNotClientPend;

    }
}
