//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class SolicitudCredito
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl amountDisplay;
        protected global::System.Web.UI.WebControls.TextBox sliderMonto;
        protected global::System.Web.UI.WebControls.HiddenField selectedCuotas;
        protected global::System.Web.UI.WebControls.HiddenField selectedPrimerPago;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Label lblInteres;
        protected global::System.Web.UI.WebControls.HiddenField hfMonto;
        protected global::System.Web.UI.WebControls.Label lblErrorMotivo;
        protected global::System.Web.UI.HtmlControls.HtmlTextArea motivoSolicitud;
    }
}
