//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class VisualizarCreditos
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlForm mainForm;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.TextBox txtFechaInicio;
        protected global::System.Web.UI.WebControls.TextBox txtFechaFin;
        protected global::System.Web.UI.WebControls.TextBox txtEstado;
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        protected global::System.Web.UI.WebControls.GridView gvCreditos;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Button btnPagar;
        protected global::System.Web.UI.WebControls.Button btnVerDetalle;
        protected global::System.Web.UI.WebControls.FileUpload fileUpload;
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;
        protected global::System.Web.UI.WebControls.DropDownList ddlMetodoPago;
        protected global::System.Web.UI.WebControls.DropDownList ddlBancoElegido;
        protected global::System.Web.UI.WebControls.TextBox txtCCI;
        protected global::System.Web.UI.WebControls.TextBox txtTitularBanco;
        protected global::System.Web.UI.WebControls.TextBox txtTipoCuenta;
        protected global::System.Web.UI.HtmlControls.HtmlSelect metodoPago;
        protected global::System.Web.UI.HtmlControls.HtmlSelect bancoElegido;
        protected global::System.Web.UI.WebControls.TextBox txtTitularBilletera;
        protected global::System.Web.UI.WebControls.TextBox txtNumeroBilletera;






    }
}
