//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWATesterC_.WSSupervisor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", ConfigurationName="WSSupervisor.SupervisorWS")]
    public interface SupervisorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/listarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/listarSupervisorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWATesterC_.WSSupervisor.listarSupervisorResponse listarSupervisor(CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/listarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/listarSupervisorResponse")]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.listarSupervisorResponse> listarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest request);
        
        // CODEGEN: El parámetro 'idSupervisor' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/eliminarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/eliminarSupervisorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorResponse eliminarSupervisor(CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/eliminarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/eliminarSupervisorResponse")]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorResponse> eliminarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest request);
        
        // CODEGEN: El parámetro 'credito' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/insertarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/insertarSupervisorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorResponse insertarSupervisor(CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/insertarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/insertarSupervisorResponse")]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorResponse> insertarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest request);
        
        // CODEGEN: El parámetro 'idSupervisor' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/modificarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/modificarSupervisorResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorResponse modificarSupervisor(CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/modificarSupervisorRequest", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/modificarSupervisorResponse" +
            "")]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorResponse> modificarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/obtenerSupervisorPorIdReque" +
            "st", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/obtenerSupervisorPorIdRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdResponse obtenerSupervisorPorId(CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.creditomovil.pucp.edu.pe/SupervisorWS/obtenerSupervisorPorIdReque" +
            "st", ReplyAction="http://services.creditomovil.pucp.edu.pe/SupervisorWS/obtenerSupervisorPorIdRespo" +
            "nse")]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdResponse> obtenerSupervisorPorIdAsync(CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/")]
    public partial class supervisor : usuario {
        
        private string agenciaAsignacionField;
        
        private string codigoEvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agenciaAsignacion {
            get {
                return this.agenciaAsignacionField;
            }
            set {
                this.agenciaAsignacionField = value;
                this.RaisePropertyChanged("agenciaAsignacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoEv {
            get {
                return this.codigoEvField;
            }
            set {
                this.codigoEvField = value;
                this.RaisePropertyChanged("codigoEv");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apMaternoField;
        
        private string apPaternoField;
        
        private string contrasenhaField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private System.DateTime ultimoLogueoField;
        
        private bool ultimoLogueoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apMaterno {
            get {
                return this.apMaternoField;
            }
            set {
                this.apMaternoField = value;
                this.RaisePropertyChanged("apMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apPaterno {
            get {
                return this.apPaternoField;
            }
            set {
                this.apPaternoField = value;
                this.RaisePropertyChanged("apPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime ultimoLogueo {
            get {
                return this.ultimoLogueoField;
            }
            set {
                this.ultimoLogueoField = value;
                this.RaisePropertyChanged("ultimoLogueo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ultimoLogueoSpecified {
            get {
                return this.ultimoLogueoFieldSpecified;
            }
            set {
                this.ultimoLogueoFieldSpecified = value;
                this.RaisePropertyChanged("ultimoLogueoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSupervisor", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSupervisorRequest {
        
        public listarSupervisorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSupervisorResponse", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSupervisorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWATesterC_.WSSupervisor.supervisor[] @return;
        
        public listarSupervisorResponse() {
        }
        
        public listarSupervisorResponse(CreditoMovilWATesterC_.WSSupervisor.supervisor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSupervisor", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarSupervisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSupervisor;
        
        public eliminarSupervisorRequest() {
        }
        
        public eliminarSupervisorRequest(int idSupervisor) {
            this.idSupervisor = idSupervisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSupervisorResponse", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarSupervisorResponse {
        
        public eliminarSupervisorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSupervisor", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSupervisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWATesterC_.WSSupervisor.supervisor credito;
        
        public insertarSupervisorRequest() {
        }
        
        public insertarSupervisorRequest(CreditoMovilWATesterC_.WSSupervisor.supervisor credito) {
            this.credito = credito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSupervisorResponse", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSupervisorResponse {
        
        public insertarSupervisorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSupervisor", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSupervisorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSupervisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWATesterC_.WSSupervisor.supervisor supervisor;
        
        public modificarSupervisorRequest() {
        }
        
        public modificarSupervisorRequest(int idSupervisor, CreditoMovilWATesterC_.WSSupervisor.supervisor supervisor) {
            this.idSupervisor = idSupervisor;
            this.supervisor = supervisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSupervisorResponse", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSupervisorResponse {
        
        public modificarSupervisorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSupervisorPorId", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerSupervisorPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSupervisor;
        
        public obtenerSupervisorPorIdRequest() {
        }
        
        public obtenerSupervisorPorIdRequest(int idSupervisor) {
            this.idSupervisor = idSupervisor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSupervisorPorIdResponse", WrapperNamespace="http://services.creditomovil.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerSupervisorPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.creditomovil.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CreditoMovilWATesterC_.WSSupervisor.supervisor @return;
        
        public obtenerSupervisorPorIdResponse() {
        }
        
        public obtenerSupervisorPorIdResponse(CreditoMovilWATesterC_.WSSupervisor.supervisor @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupervisorWSChannel : CreditoMovilWATesterC_.WSSupervisor.SupervisorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupervisorWSClient : System.ServiceModel.ClientBase<CreditoMovilWATesterC_.WSSupervisor.SupervisorWS>, CreditoMovilWATesterC_.WSSupervisor.SupervisorWS {
        
        public SupervisorWSClient() {
        }
        
        public SupervisorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupervisorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupervisorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupervisorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWATesterC_.WSSupervisor.listarSupervisorResponse CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.listarSupervisor(CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest request) {
            return base.Channel.listarSupervisor(request);
        }
        
        public CreditoMovilWATesterC_.WSSupervisor.supervisor[] listarSupervisor() {
            CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest();
            CreditoMovilWATesterC_.WSSupervisor.listarSupervisorResponse retVal = ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).listarSupervisor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.listarSupervisorResponse> CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.listarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest request) {
            return base.Channel.listarSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.listarSupervisorResponse> listarSupervisorAsync() {
            CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.listarSupervisorRequest();
            return ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).listarSupervisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorResponse CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.eliminarSupervisor(CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest request) {
            return base.Channel.eliminarSupervisor(request);
        }
        
        public void eliminarSupervisor(int idSupervisor) {
            CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest();
            inValue.idSupervisor = idSupervisor;
            CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorResponse retVal = ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).eliminarSupervisor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorResponse> CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.eliminarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest request) {
            return base.Channel.eliminarSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorResponse> eliminarSupervisorAsync(int idSupervisor) {
            CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.eliminarSupervisorRequest();
            inValue.idSupervisor = idSupervisor;
            return ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).eliminarSupervisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorResponse CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.insertarSupervisor(CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest request) {
            return base.Channel.insertarSupervisor(request);
        }
        
        public void insertarSupervisor(CreditoMovilWATesterC_.WSSupervisor.supervisor credito) {
            CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest();
            inValue.credito = credito;
            CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorResponse retVal = ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).insertarSupervisor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorResponse> CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.insertarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest request) {
            return base.Channel.insertarSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorResponse> insertarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.supervisor credito) {
            CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.insertarSupervisorRequest();
            inValue.credito = credito;
            return ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).insertarSupervisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorResponse CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.modificarSupervisor(CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest request) {
            return base.Channel.modificarSupervisor(request);
        }
        
        public void modificarSupervisor(int idSupervisor, CreditoMovilWATesterC_.WSSupervisor.supervisor supervisor) {
            CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest();
            inValue.idSupervisor = idSupervisor;
            inValue.supervisor = supervisor;
            CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorResponse retVal = ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).modificarSupervisor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorResponse> CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.modificarSupervisorAsync(CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest request) {
            return base.Channel.modificarSupervisorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorResponse> modificarSupervisorAsync(int idSupervisor, CreditoMovilWATesterC_.WSSupervisor.supervisor supervisor) {
            CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.modificarSupervisorRequest();
            inValue.idSupervisor = idSupervisor;
            inValue.supervisor = supervisor;
            return ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).modificarSupervisorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdResponse CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.obtenerSupervisorPorId(CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest request) {
            return base.Channel.obtenerSupervisorPorId(request);
        }
        
        public CreditoMovilWATesterC_.WSSupervisor.supervisor obtenerSupervisorPorId(int idSupervisor) {
            CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest();
            inValue.idSupervisor = idSupervisor;
            CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdResponse retVal = ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).obtenerSupervisorPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdResponse> CreditoMovilWATesterC_.WSSupervisor.SupervisorWS.obtenerSupervisorPorIdAsync(CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest request) {
            return base.Channel.obtenerSupervisorPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdResponse> obtenerSupervisorPorIdAsync(int idSupervisor) {
            CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest inValue = new CreditoMovilWATesterC_.WSSupervisor.obtenerSupervisorPorIdRequest();
            inValue.idSupervisor = idSupervisor;
            return ((CreditoMovilWATesterC_.WSSupervisor.SupervisorWS)(this)).obtenerSupervisorPorIdAsync(inValue);
        }
    }
}
